name: Deploy to Hostwinds

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
    # Step 1: Check out the latest code from the main branch
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Connect to the Hostwinds server via SSH and deploy the app
    - name: Deploy to Hostwinds server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOSTWINDS_IP }}
        username: ${{ secrets.HOSTWINDS_SSH_USER }}
        key: ${{ secrets.HOSTWINDS_SSH_KEY }}
        passphrase: ''
        script: |
          cd ~/yousound # Go to the app directory on the server
          
          # Pull the latest changes from the main branch
          git pull origin main
          
          # Install dependencies (main folder or subfolders if needed)
          npm install

          # Optional: If you have separate package.json files for frontend and server
          cd frontend
          npm install
          cd ../server
          npm install
          cd ..

          # Start or restart the app in production mode with PM2
          pm2 start npm --name "yousound" -- start --env production || pm2 restart "yousound"
